go_library(
    name = "constants",
    srcs = glob(
        ["*.go"],
        exclude = ["*_test.go"],
    ),
    visibility = [
        "//entities:all",
        "//requests:all",
        "//responses:all",
    ],
)
