go_library(
    name = "constants",
    srcs = [
        "differential_query.go",
        "harbormaster.go",
        "maniphest_query.go",
        "phid_types.go",
        "project_query.go",
        "remarkup.go",
        "search.go",
    ],
    visibility = [
        "//entities:all",
        "//requests:all",
        "//responses:all",
    ],
)
