go_default_library(
    external_test = True,
    deps = [
        "//constants",
        "//util",
    ],
    test_deps = [
        "//third_party/go:ginkgo",
        "//third_party/go:gomega",
    ],
)
