go_default_library(
    deps = [
        "//requests",
        "//responses",
        "//third_party/go:typed",
    ],
    test_deps = [
        "//third_party/go:gin",
        "//third_party/go:testify",
    ],
)
